---
- name: Install python3 and dependencies
  apt: name={{item}} state=present
    update_cache: yes
  with_items:
    - python-pip
    - python-dev
    - libpq-dev
    - python3-pip
    - python3-dev
    - python3-venv
    - libtiff5-dev
    - libjpeg8-dev
    - zlib1g-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.6-dev
    - tk8.6-dev
    - python-tk